server:
  port : 5000

spring:
  jpa:
    hibernate:
    ddl-auto: none
  datasource:
    url: ${bdUrl}
    username: ${dbUserName}
    password: ${dbPassword}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    encoding: UTF-8
    locations: classpath:db/migration
    validate-on-migrate: true

telegram:
  botName: ${botName}
  botToken: ${botToken}
  chatPort: ${chatPort}
  chatHost: ${chatHost}
